version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - ENGINE_DB=${ENGINE_DB}
      - NAME_DB=${NAME_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
    command: gunicorn main.wsgi:application -b 0.0.0.0:8000

    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles  # Share staticfiles
      - media_volume:/app/media  # Share media files
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static  # Mount staticfiles for Nginx
      - media_volume:/usr/share/nginx/html/media  # Mount media files for Nginx
    networks:
      - app_network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # Optional
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:
  media_volume: 

networks:
  app_network:
    driver: bridge

