# Generated by Django 5.1.3 on 2025-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Building", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_img",
            field=models.ImageField(blank=True, null=True, upload_to="building"),
        ),
    ]
