# Generated by Django 5.1.3 on 2025-03-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Building", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "heat_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "electric_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "internet_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "noise_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("air_status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "neighborhood_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Building.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Building.room"
                    ),
                ),
            ],
        ),
    ]
