# Generated by Django 5.2.3 on 2025-08-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_report',
            name='air_quality_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='cleanliness_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='draft_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='lighting_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='odor_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_report', to='Building.organization'),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_report', to='Building.room'),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='structural_change_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room_report',
            name='temperature_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor_report',
            name='created_at',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='sensor_report',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
